
server:
  port: 8006
  servlet:
    context-path: /dynamicdatasource


spring:
  application:
    name: dynamicdatasource
  datasource:
#    url: jdbc:mysql://localhost:3306/test_yl?serverTimezone=Asia/Shanghai
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.jdbc.Driver

    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      url:
      username:
      password:
      ### 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 5
      ### 最小连接池数量
      min-idle: 10
      max-evictable-idle-time-millis: 900000
      ### 有两个含义：（1) Destroy线程会检测连接的间隔时间 （2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      ### 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 60000
      ### 最大连接池数量
      max-active: 100
      ### 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。作者在5.5版本中使用PSCache，通过监控界面发现PSCache有缓存命中率记录， 该应该是支持PSCache。
      pool-prepared-statements: true
      ### 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      ### 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      ### 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      ### 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: SELECT 1
      stat-view-servlet:
        enabled: true
        url-pattern: /monitor/druid/*
      ### 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      filter: stat
      connect-properties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true




  thymeleaf:
    prefix:
      classpath: /templates/
    cache: false
    suffix:  .html
  security:
    user:
      name: 1
      password: 1



# mybatis的配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapping/*.xml
  # 搜索指定包别名
  type-aliases-package: com.yl.dynamicdatasource


##未知
release:
  url:
    - '/home'
    - '/hello'


# 日志配置
logging:
  level:
    com.yl: debug
    org.springframework: warn
